[mypy]
ignore_missing_imports = True
no_strict_optional = True
show_error_codes = True
warn_unused_ignores = False

[mypy-server.kuro_engine]
disable_error_code = arg-type, assignment, index

[mypy-server.process.tts_func.sovits_amd]
disable_error_code = import-untyped

[mypy-voice.*]
disable_error_code = misc, attr-defined

[mypy-tests.*]
disable_error_code = arg-type, assignment, return-value, index, import-untyped

[mypy-avatar.*]
disable_error_code = assignment

[mypy-bot_main]
disable_error_code = assignment, operator
